In [1]:
import numpy as np

def standardize(X):
    return (X - np.mean(X, axis=0)) / np.std(X, axis=0)

def compute_covariance_matrix(X):
    return np.cov(X.T)

def find_eigenvectors_and_eigenvalues(X):
    cov_matrix = compute_covariance_matrix(X)
    eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
    return eigenvalues, eigenvectors

def project_data(X, eigenvectors, k):
    sorted_eigenvectors = eigenvectors[:, np.argsort(-np.abs(np.linalg.eigvals(compute_covariance_matrix(X))))[:k]]
    return np.dot(X, sorted_eigenvectors)

def get_variance_explained(eigenvalues, k):
    return sum(eigenvalues[:k]) / sum(eigenvalues)

X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
X_std = standardize(X)
eigenvalues, eigenvectors = find_eigenvectors_and_eigenvalues(X_std)
projected_data = project_data(X_std, eigenvectors, 2)
variance_explained = get_variance_explained(eigenvalues, 2)

print("Standardized data:")
print(X_std)
print("Covariance matrix:")
print(compute_covariance_matrix(X_std))
print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)
print("Projected data:")
print(projected_data)
print("Variance explained:")
print(variance_explained)


Standardized data:
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
Covariance matrix:
[[1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]]
Eigenvalues:
[0.  4.5 0. ]
Eigenvectors:
[[-0.81649658  0.57735027  0.        ]
 [ 0.40824829  0.57735027 -0.70710678]
 [ 0.40824829  0.57735027  0.70710678]]
Projected data:
[[-2.12132034e+00  1.06617010e-16]
 [ 0.00000000e+00  0.00000000e+00]
 [ 2.12132034e+00 -1.06617010e-16]]
Variance explained:
1.0
