In [1]:
import numpy as np

dataset = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

covariance_matrix = np.cov(dataset, rowvar=False)

print("Covariance Matrix:")
print(covariance_matrix)


Covariance Matrix:
[[15. 15. 15.]
 [15. 15. 15.]
 [15. 15. 15.]]
